name: Export Project
on:
  workflow_dispatch:
    inputs:
      game_dir:
        description: 'version of demo game'
        required: true
        type: string
        default: 'test_project'

env:
  EXPORT_NAME: cool_godot_game-${{ inputs.game_dir }} # change this to whatever you like
jobs: 
  build_project_linux:
    name: Build Project (Linux)
    runs-on: ubuntu-latest
    container:
      image: witchpixels/godot4-omnibuilder3d:latest-4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      # You only need this for Github Actions, Gitlab works out of the box
      - name: Fix paths for Github
        run: setup_github_paths.sh

      - name: Linux Build
        working-directory: ${{ inputs.game_dir }}
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: ${{ inputs.game_dir }}/build/linux

  build_project_windows:
    name: Build Project (Windows Desktop)
    runs-on: ubuntu-latest
    container:
      image: witchpixels/godot4-omnibuilder3d:latest-4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      # You only need this for Github Actions, Gitlab works out of the box
      - name: Fix paths for Github
        run: setup_github_paths.sh

      - name: Windows Build
        working-directory: ${{ inputs.game_dir }}
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-windows
          path: ${{ inputs.game_dir }}/build/windows