name: Export Project
on:
  workflow_dispatch:
    inputs:
      game_dir:
        description: 'version of demo game'
        required: true
        type: string
        default: 'game1'
        
env:
  EXPORT_NAME: cool_godot_game # change this to whatever you like
jobs: 
  build_project_linux:
    name: Build Project (Linux)
    runs-on: ubuntu-latest
    container:
      image: witchpixels/godot4-omnibuilder3d:latest-4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true

      # You only need this for Github Actions, Gitlab works out of the box
      - name: Fix paths for Github
        run: setup_github_paths.sh

      - name: Linux Build
        working-directory: test_project
        run: |
          mkdir -v -p build/linux
          godot -v --headless --export-release "Linux/X11" build/linux/$EXPORT_NAME.x86_64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-linux
          path: test_project/build/linux